In [ ]:
from sklearn.datasets import fetch_openml
import numpy as np
import pandas as pd
mnist = fetch_openml('mnist_784', version=1)

### Poprawne zbiory danych +97% acc

In [37]:
from sklearn.model_selection import train_test_split
X, y = mnist.data, mnist.target.astype(np.uint8)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)


(56000, 784) (56000,) (14000, 784) (14000,)


In [38]:
pd.unique(y_train.sort_values()), pd.unique(y_test.sort_values())

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8))

In [40]:
from sklearn.linear_model import SGDClassifier
y_train_0 = (y_train == 0)
y_test_0 = (y_test == 0)
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train_0)


SGDClassifier(random_state=42)

In [42]:
sgd_clf.score(X_train, y_train_0), sgd_clf.score(X_test, y_test_0)

(0.9901964285714285, 0.9877857142857143)

In [44]:
import pickle
pickle.dump([sgd_clf.score(X_train, y_train_0), sgd_clf.score(X_test, y_test_0)], open("sgd_acc.pkl", "wb"))

In [50]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix


In [47]:
y_train_score = cross_val_score(sgd_clf, X_train, y_train_0, cv=3, n_jobs=-1)
y_train_score

array([0.98650024, 0.98950019, 0.98542805])

In [48]:
pickle.dump(y_train_score, open("sgd_cva.pkl", "wb"))

In [52]:
sgd_clf_all = SGDClassifier(random_state=42)
sgd_clf_all.fit(X_train, y_train)


SGDClassifier(random_state=42)

In [53]:
y_train_predict_all = cross_val_predict(sgd_clf_all, X_train, y_train, cv=3, n_jobs=-1)
y_train_predict_all

array([3, 0, 4, ..., 2, 6, 8], dtype=uint8)

In [54]:
conf_mx = confusion_matrix(y_train, y_train_predict_all)
conf_mx

array([[5297,    0,   53,   24,    9,   25,   53,    2,   56,   11],
       [   3, 6078,   64,   54,    8,   14,    9,   19,   48,   11],
       [  55,   67, 4669,  246,   53,   26,  101,   85,  247,   11],
       [  42,   15,  170, 4884,   14,  152,   31,   65,  308,   47],
       [  10,   31,   62,   31, 4918,   20,   60,   33,  159,  124],
       [  97,   28,   68,  369,  102, 3766,  168,   22,  364,   76],
       [  54,   16,   83,   19,   58,   46, 5203,    3,   54,    1],
       [  20,   20,   70,  105,   72,   11,    6, 5271,   79,  156],
       [  81,  129,  151,  385,   61,  110,   64,   35, 4382,   62],
       [  44,   30,   32,  129,  415,   47,    1,  376,  274, 4211]],
      dtype=int64)

In [ ]:
pickle.dump(conf_mx, open("sgd_cmx.pkl", "wb"))