In [7]:
from sklearn.datasets import fetch_openml
import numpy as np
mnist = fetch_openml('mnist_784', version=1)

In [8]:
print((np.array(mnist.data.loc[42]).reshape(28, 28) > 0).astype(int))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 

In [27]:
import pandas as pd
y = pd.Series(mnist.target.astype(np.uint8))
X = mnist.data
y = y.sort_values(ascending=True)


In [28]:
y.index

Int64Index([34999, 56424, 56419, 16705, 56415, 56404, 56397, 56389, 56388,
            56429,
            ...
            13698, 33531, 13695, 13692, 58898, 13687, 42651, 58914, 13678,
            58529],
           dtype='int64', length=70000)

In [30]:
X.reindex(y.index)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
34999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56424     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56419     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
16705     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56415     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
13687     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
42651     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58914     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
13678     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58529     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
34999      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56424      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56419      0.0  ...       0.0       0.0       0.0       0.0       0.0   
16705      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56415      0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
13687      0.0  ...       0.0       0.0       0.0       0.0       0.0   
42651      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58914      0.0  ...       0.0       0.0       0.0       0.0       0.0   
13678      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58529      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
34999       0.0       0.0       0.0       0.0       0.0  
56424       0.0       0.0       0.0       0.0       0.0  
56419       0.0       0.0       0.0       0.0       0.0  
16705       0.0       0.0       0.0       0.0       0.0  
56415       0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
13687       0.0       0.0       0.0       0.0       0.0  
42651       0.0       0.0       0.0       0.0       0.0  
58914       0.0       0.0       0.0       0.0       0.0  
13678       0.0       0.0       0.0       0.0       0.0  
58529       0.0       0.0       0.0       0.0       0.0  

[70000 rows x 784 columns]

In [30]:
X.reindex(y.index)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
34999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56424     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56419     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
16705     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56415     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
13687     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
42651     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58914     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
13678     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58529     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
34999      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56424      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56419      0.0  ...       0.0       0.0       0.0       0.0       0.0   
16705      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56415      0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
13687      0.0  ...       0.0       0.0       0.0       0.0       0.0   
42651      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58914      0.0  ...       0.0       0.0       0.0       0.0       0.0   
13678      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58529      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
34999       0.0       0.0       0.0       0.0       0.0  
56424       0.0       0.0       0.0       0.0       0.0  
56419       0.0       0.0       0.0       0.0       0.0  
16705       0.0       0.0       0.0       0.0       0.0  
56415       0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
13687       0.0       0.0       0.0       0.0       0.0  
42651       0.0       0.0       0.0       0.0       0.0  
58914       0.0       0.0       0.0       0.0       0.0  
13678       0.0       0.0       0.0       0.0       0.0  
58529       0.0       0.0       0.0       0.0       0.0  

[70000 rows x 784 columns]

In [31]:
 X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(56000, 784) (56000,)
(14000, 784) (14000,)


In [33]:
y_train, y_test

(34999    0
 56424    0
 56419    0
 16705    0
 56415    0
         ..
 20694    7
 68173    7
 50920    7
 49301    7
 69650    7
 Name: class, Length: 56000, dtype: uint8,
 53213    7
 53313    7
 51502    7
 29282    7
 53333    7
         ..
 13687    9
 42651    9
 58914    9
 13678    9
 58529    9
 Name: class, Length: 14000, dtype: uint8)

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [41]:
pd.unique(y_train.sort_values()), pd.unique(y_test.sort_values())

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8))

In [45]:
from sklearn.linear_model import SGDClassifier
y_train_0 = (y_train == 0)
y_test_0 = (y_test == 0)

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train_0)


array([False, False, False, ..., False, False, False])

In [46]:
a = sgd_clf.predict(X_train)
b = sgd_clf.predict(X_test)


In [72]:
pickle.dump([sgd_clf.score(X_train, y_train_0), sgd_clf.score(X_test, y_test_0)], open("sgd_acc.pkl", "wb"))

In [75]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix

In [79]:
y_train_score = cross_val_score(sgd_clf, X_train, y_train_0, cv=3, n_jobs=-1)

In [80]:
pickle.dump(y_train_score, open("sgd_cva.pkl", "wb"))

In [81]:
sgd_clf_all = SGDClassifier(random_state=42)
sgd_clf_all.fit(X_train, y_train)


SGDClassifier(random_state=42)

In [ ]:
y_train_predict_all = cross_val_predict(sgd_clf_all, X_train, y_train, cv=3, n_jobs=-1)


In [ ]:
conf_mx = confusion_matrix(y_train, y_train_predict_all)

In [ ]:
pickle.dump(conf_mx, open("sgd_cmx.pkl", "wb"))