In [1]:
from sklearn.datasets import fetch_openml
import numpy as np
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
mnist.target = mnist.target.astype(np.uint8)
X = mnist["data"]
y = mnist["target"]

In [3]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
clusters = []
sil_clusters = []
for x in range(8,13):
    kmeans = KMeans(n_clusters=x)
    kmeans.fit(X)
    clusters.append(kmeans)
    a = silhouette_score(X, kmeans.labels_)
    sil_clusters.append(a)




0.07338441611681432


KeyboardInterrupt: 

In [ ]:
import pickle
pickle.dump(sil_clusters, open("kmeans_sil.pkl", "wb"))

In [4]:
from sklearn.metrics import confusion_matrix
from sklearn.cluster import KMeans
km_10_confmat = set()
kmeans_10 = clusters[2]
y_pred = kmeans_10.predict(X)
conf = confusion_matrix(y, y_pred)
print(conf)
for row in conf:
    km_10_confmat.add(np.argmax(row))
    
print(km_10_confmat)
km_10_confmat = list(km_10_confmat)

[[   9    7 1265   72    2  290  162   39    4 5053]
 [  10   11    7    8 4293    8    7    7 3526    0]
 [4863   78  246  201  423  323  147  216  436   57]
 [ 215   45  462 1083  449 4581   31  193   58   24]
 [  29 2173  288   17  178    0  168 3728  234    9]
 [   7  215 1811 1157  155 2129   67  432  280   60]
 [  53    4 2070   14  190   38 4324   67   45   71]
 [  53 4399   12   18  372    6    4 2094  314   21]
 [  53  194  291 4115  335 1212   51  208  330   36]
 [  19 2849   31   87  261   87   16 3462   95   51]]
{0, 1, 3, 4, 5, 6, 7, 9}


In [ ]:
pickle.dump(km_10_confmat, open("kmeans_argmax.pkl", "wb"))

In [5]:
data = []
for x in X[:300]:
    for x2 in X:
        data.append(np.linalg.norm(x-x2))
    


In [7]:
smallest = np.sort(data)[300:310]
smallest

array([279.26152617, 304.3764117 , 317.5893575 , 328.76587414,
       333.45464459, 352.89800226, 355.17742045, 358.0740147 ,
       359.64287842, 360.42474943])

In [ ]:
pickle.dump(smallest, open("dist.pkl", "wb"))

In [12]:
b = np.average(smallest[:3])
from sklearn.cluster import DBSCAN
s = b
dbscan_len = []
while s<=b+0.1*b:
    dbsc=DBSCAN(eps=s)
    dbsc.fit(X)
    dbscan_len.append(len(np.unique(dbsc.labels_)))
    s+=0.04*s

[-1  0  1  2]
[-1  0  1  2  3  4  5]
[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


In [ ]:
pickle.dump(dbscan_len, open("dbscan_len.pkl", "wb"))